name: 'Publish EIP Lookup'
on:
  workflow_dispatch:
    inputs:
      version:
        required: true

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - name: Set variables
      id: set_variables
      run: |
        # if workflow input is set, use that. otherwise default to "release-$(datestr)"
        release_name=${{ github.event.inputs.version }}
        echo "release_name=$release_name" >> $GITHUB_OUTPUT
    - name: Checkout
      uses: actions/checkout@v3
    - name: Build release
      run: |
        cargo build --release
    - name: Create release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          target/release/eip-lookup
        name: ${{ steps.set_variables.outputs.release_name }}
        tag_name: ${{ steps.set_variables.outputs.release_name }}
        draft: false
        prerelease: false
        token: ${{ secrets.TOKEN }}